package lib

import (
	"path/filepath"
	"strings"
)

type CppCodeGenerator struct {
	BaseCodeGenerator
}

func NewCppCodeGenerator() *CppCodeGenerator {
	newObj := new(CppCodeGenerator)

	return newObj
}

func (this *CppCodeGenerator) Close() {
	this.close()
}

func (this *CppCodeGenerator) Generate(
	descriptor *TableDescriptor,
	reader string, outputDir string, newLineType NewLineType) bool {

	this.init(descriptor, reader, newLineType)

	for _, def := range this.descriptor.GlobalStructs {
		underscoreName := UtilCamelToUnderscore(def.Name)

		headerFilePath := filepath.Join(outputDir, underscoreName+".h")
		headerFileContent := this.generateGlobalStructHeaderFile(def)
		if UtilWriteAllText(headerFilePath, headerFileContent) == false {
			return false
		}

		sourceFilePath := filepath.Join(outputDir, underscoreName+".cc")
		sourceFileContent := this.generateGlobalStructSourceFile(def)
		if UtilWriteAllText(sourceFilePath, sourceFileContent) == false {
			return false
		}
	}

	return true
}

func (this *CppCodeGenerator) getStructFieldCppType(
	fieldDef *StructFieldDef) string {

	cppType := ""

	if fieldDef.Type == StructFieldType_Int {
		cppType = "int32_t"
	} else if fieldDef.Type == StructFieldType_String {
		cppType = "std::string"
	}

	return cppType
}

func (this *CppCodeGenerator) generateGlobalStructHeaderFile(
	structDef *StructDef) string {

	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeGlobalStructHeaderFileIncludeGuardStart(&sb, structDef)
	this.writeGlobalStructHeaderFileIncludeFileDecl(&sb, structDef)
	this.writeNamespaceDeclStart(&sb)
	this.writeHeaderFileOneStructDecl(&sb, structDef)
	this.writeNamespaceDeclEnd(&sb)
	this.writeGlobalStructHeaderFileIncludeGuardEnd(&sb)

	return sb.String()
}

func (this *CppCodeGenerator) generateGlobalStructSourceFile(
	structDef *StructDef) string {

	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeGlobalStructSourceFileIncludeFileDecl(&sb, structDef)
	this.writeNamespaceDeclStart(&sb)
	this.writeSourceFileOneStructImpl(&sb, structDef)
	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CppCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb,
		"/*")
	this.writeLine(sb,
		" * Generated by brickred table compiler.")
	this.writeLine(sb,
		" * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb,
		" */")
}

func (this *CppCodeGenerator) writeNamespaceDeclStart(
	sb *strings.Builder) {

	readerDef, ok := this.descriptor.Readers[this.reader]
	if ok == false {
		return
	}
	namespaceName := strings.Join(readerDef.NamespaceParts, "::")

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"namespace %s {",
		namespaceName)
}

func (this *CppCodeGenerator) writeNamespaceDeclEnd(
	sb *strings.Builder) {

	readerDef, ok := this.descriptor.Readers[this.reader]
	if ok == false {
		return
	}
	namespaceName := strings.Join(readerDef.NamespaceParts, "::")

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"} // namespace %s",
		namespaceName)
}

func (this *CppCodeGenerator) writeHeaderFileOneStructDecl(
	sb *strings.Builder, structDef *StructDef) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"class %s {",
		structDef.Name)
	this.writeLine(sb,
		"public:")
	this.writeLineFormat(sb,
		"    %s();",
		structDef.Name)
	this.writeLineFormat(sb,
		"    ~%s();",
		structDef.Name)
	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"    bool parse(const std::string &text);")

	if len(structDef.Fields) > 0 {
		this.writeEmptyLine(sb)
		this.writeLine(sb,
			"public:")

		for _, def := range structDef.Fields {
			cppType := this.getStructFieldCppType(def)
			this.writeLineFormat(sb,
				"    %s %s;",
				cppType, def.Name)
		}
	}

	this.writeLine(sb,
		"};")
}

func (this *CppCodeGenerator) writeSourceFileOneStructImpl(
	sb *strings.Builder, structDef *StructDef) {

	this.writeSourceFileOneStructImplConstructor(sb, structDef)
	this.writeSourceFileOneStructImplDestructor(sb, structDef)
}

func (this *CppCodeGenerator) writeSourceFileOneStructImplConstructor(
	sb *strings.Builder, structDef *StructDef) {

	hasInitList := false
	lastInitListFieldIndex := -1

	for i, def := range structDef.Fields {
		if def.Type == StructFieldType_String {
			continue
		}
		hasInitList = true
		lastInitListFieldIndex = i
	}

	this.writeEmptyLine(sb)
	if hasInitList {
		this.writeLineFormat(sb,
			"%s::%s() :",
			structDef.Name, structDef.Name)
	} else {
		this.writeLineFormat(sb,
			"%s::%s()",
			structDef.Name, structDef.Name)
	}

	if hasInitList {
		for i, def := range structDef.Fields {
			var defaultValue string
			if def.Type == StructFieldType_Int {
				defaultValue = "0"
			} else {
				continue
			}

			if i == lastInitListFieldIndex {
				this.writeLineFormat(sb,
					"    %s(%s)",
					def.Name, defaultValue)
			} else {
				this.writeLineFormat(sb,
					"    %s(%s),",
					def.Name, defaultValue)
			}
		}
	}

	this.writeLine(sb,
		"{")
	this.writeLine(sb,
		"}")
}

func (this *CppCodeGenerator) writeSourceFileOneStructImplDestructor(
	sb *strings.Builder, structDef *StructDef) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s::~%s()",
		structDef.Name, structDef.Name)
	this.writeLine(sb,
		"{")
	this.writeLine(sb,
		"}")
}

func (this *CppCodeGenerator) writeGlobalStructHeaderFileIncludeGuardStart(
	sb *strings.Builder, structDef *StructDef) {

	guardNameParts := make([]string, 0)
	guardNameParts = append(guardNameParts, "BRICKRED_TABLE_GENERATED")
	readerDef, ok := this.descriptor.Readers[this.reader]
	if ok {
		guardNameParts = append(
			guardNameParts, readerDef.NamespaceParts...)
	}
	guardNameParts = append(guardNameParts,
		g_notWordRegexp.ReplaceAllString(
			UtilCamelToUnderscore(structDef.Name), "_"))
	guardNameParts = append(guardNameParts, "H")
	guardName := strings.ToUpper(strings.Join(guardNameParts, "_"))

	this.writeLineFormat(sb,
		"#ifndef %s",
		guardName)
	this.writeLineFormat(sb,
		"#define %s",
		guardName)
}

func (this *CppCodeGenerator) writeGlobalStructHeaderFileIncludeGuardEnd(
	sb *strings.Builder) {

	this.writeEmptyLine(sb)
	this.writeLine(sb,
		"#endif")
}

func (this *CppCodeGenerator) writeGlobalStructHeaderFileIncludeFileDecl(
	sb *strings.Builder, structDef *StructDef) {

	useCStdIntH := false

	for _, def := range structDef.Fields {
		if def.Type == StructFieldType_Int {
			useCStdIntH = true
		}
	}

	this.writeEmptyLine(sb)
	if useCStdIntH {
		this.writeLine(sb,
			"#include <cstdint>")
	}
	this.writeLine(sb,
		"#include <string>")
}

func (this *CppCodeGenerator) writeGlobalStructSourceFileIncludeFileDecl(
	sb *strings.Builder, structDef *StructDef) {

	this.writeLineFormat(sb,
		"#include \"%s.h\"",
		UtilCamelToUnderscore(structDef.Name))
	this.writeEmptyLine(sb)
	this.writeLine(sb,
		"#include <brickred/table/column_spliter.h>")
}
