package lib

import (
	"fmt"
	"path/filepath"
	"strings"
)

type CSharpCodeGenerator struct {
	BaseCodeGenerator
}

func NewCSharpCodeGenerator() *CSharpCodeGenerator {
	newObj := new(CSharpCodeGenerator)

	return newObj
}

func (this *CSharpCodeGenerator) Close() {
	this.close()
}

func (this *CSharpCodeGenerator) Generate(
	descriptor *TableDescriptor,
	reader string, outputDir string, newLineType NewLineType) bool {

	this.init(descriptor, reader, newLineType)

	for _, def := range this.descriptor.GlobalStructs {
		filePath := filepath.Join(outputDir, def.Name+".cs")
		fileContent := this.generateGlobalStructFile(def)
		if UtilWriteAllText(filePath, fileContent) == false {
			return false
		}
	}

	for _, def := range this.descriptor.Tables {
		filePath := filepath.Join(outputDir, def.Name+".cs")
		fileContent := this.generateTableFile(def)
		if UtilWriteAllText(filePath, fileContent) == false {
			return false
		}
	}

	return true
}

func (this *CSharpCodeGenerator) getStructFieldCSharpType(
	fieldDef *StructFieldDef) string {

	csharpType := ""
	if fieldDef.Type == StructFieldType_Int {
		csharpType = "int"
	} else if fieldDef.Type == StructFieldType_String {
		csharpType = "string"
	}

	return csharpType
}

func (this *CSharpCodeGenerator) getStructFieldCSharpTypeDefaultValue(
	fieldDef *StructFieldDef) string {

	defaultValue := ""
	if fieldDef.Type == StructFieldType_Int {
		defaultValue = "0"
	} else if fieldDef.Type == StructFieldType_String {
		defaultValue = "\"\""
	}

	return defaultValue
}

func (this *CSharpCodeGenerator) getTableColumnCSharpType(
	columnDef *TableColumnDef) string {

	var checkType TableColumnType
	if columnDef.Type == TableColumnType_List {
		checkType = columnDef.ListType
	} else {
		checkType = columnDef.Type
	}

	csharpType := ""
	if checkType == TableColumnType_Int {
		csharpType = "int"
	} else if checkType == TableColumnType_String {
		csharpType = "string"
	} else if checkType == TableColumnType_Struct {
		csharpType = columnDef.RefStructDef.Name
	}

	if columnDef.Type == TableColumnType_List {
		return fmt.Sprintf("System.Collections.Generic.List<%s>", csharpType)
	} else {
		return csharpType
	}
}

func (this *CSharpCodeGenerator) getTableColumnCSharpTypeDefaultValue(
	columnDef *TableColumnDef) string {

	defaultValue := ""
	if columnDef.Type == TableColumnType_Int {
		defaultValue = "0"
	} else if columnDef.Type == TableColumnType_String {
		defaultValue = "\"\""
	} else if columnDef.Type == TableColumnType_Struct ||
		columnDef.Type == TableColumnType_List {
		defaultValue = fmt.Sprintf("new %s()",
			this.getTableColumnCSharpType(columnDef))
	}

	return defaultValue
}

func (this *CSharpCodeGenerator) generateGlobalStructFile(
	structDef *StructDef) string {

	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeNamespaceDeclStart(&sb)

	indent := this.getIndent()
	this.writeOneStructDecl(&sb, structDef, indent)

	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CSharpCodeGenerator) generateTableFile(
	tableDef *TableDef) string {

	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeNamespaceDeclStart(&sb)

	indent := this.getIndent()
	this.writeTableDecl(&sb, tableDef, indent)

	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CSharpCodeGenerator) getIndent() string {
	if _, ok := this.descriptor.Readers[this.reader]; ok {
		return "    "
	} else {
		return ""
	}
}

func (this *CSharpCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb,
		"/*")
	this.writeLine(sb,
		" * Generated by brickred table compiler.")
	this.writeLine(sb,
		" * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb,
		" */")
}

func (this *CSharpCodeGenerator) writeNamespaceDeclStart(
	sb *strings.Builder) {

	readerDef, ok := this.descriptor.Readers[this.reader]
	if ok == false {
		return
	}

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"namespace %s",
		readerDef.Namespace)
	this.writeLine(sb,
		"{")
}

func (this *CSharpCodeGenerator) writeNamespaceDeclEnd(
	sb *strings.Builder) {

	_, ok := this.descriptor.Readers[this.reader]
	if ok == false {
		return
	}

	this.writeLine(sb,
		"}")
}

func (this *CSharpCodeGenerator) writeOneStructDecl(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if structDef.ParentRef != nil {
		indent += "    "
	}

	this.writeLineFormat(sb,
		"%spublic sealed class %s : Brickred.Table.BaseStruct",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)

	this.writeOneStructDeclFieldDecl(sb, structDef, indent)
	this.writeOneStructDeclParseFunc(sb, structDef, indent)

	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclFieldDecl(
	sb *strings.Builder, structDef *StructDef, indent string) {

	for _, def := range structDef.Fields {
		csharpType := this.getStructFieldCSharpType(def)
		defaultValue := this.getStructFieldCSharpTypeDefaultValue(def)
		this.writeLineFormat(sb,
			"%s    public %s %s = %s;",
			indent, csharpType, def.Name, defaultValue)
	}
}

func (this *CSharpCodeGenerator) writeOneStructDeclParseFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if len(structDef.Fields) > 0 {
		this.writeEmptyLine(sb)
	}
	this.writeLineFormat(sb,
		"%s    public override bool Parse(string text)",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	if len(structDef.Fields) <= 0 {
		this.writeLineFormat(sb,
			"%s        return true;",
			indent)
	} else {
		this.writeLineFormat(sb,
			"%s        Brickred.Table.ColumnSpliter s =",
			indent)
		this.writeLineFormat(sb,
			"%s            new Brickred.Table.ColumnSpliter(text, ';');",
			indent)
		this.writeEmptyLine(sb)

		for _, def := range structDef.Fields {
			if def.Type == StructFieldType_Int {
				this.writeLineFormat(sb,
					"%s        if (s.NextInt(ref this.%s) == false) {",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s            return false;",
					indent)
				this.writeLineFormat(sb,
					"%s        }",
					indent)
			} else if def.Type == StructFieldType_String {
				this.writeLineFormat(sb,
					"%s        if (s.NextString(ref this.%s) == false) {",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s            return false;",
					indent)
				this.writeLineFormat(sb,
					"%s        }",
					indent)
			}
		}

		this.writeLineFormat(sb,
			"%s        if (s.NextString()) {",
			indent)
		this.writeLineFormat(sb,
			"%s            return false;",
			indent)
		this.writeLineFormat(sb,
			"%s        }",
			indent)
		this.writeEmptyLine(sb)
		this.writeLineFormat(sb,
			"%s        return true;",
			indent)
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDecl(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	this.writeLineFormat(sb,
		"%spublic sealed class %s",
		indent, tableDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)

	for _, def := range tableDef.LocalStructs {
		this.writeOneStructDecl(sb, def, indent)
		this.writeEmptyLine(sb)
	}

	this.writeTableDeclRowClassDecl(sb, tableDef, indent)
	this.writeEmptyLine(sb)
	this.writeTableDeclMemberDecl(sb, tableDef, indent)
	this.writeEmptyLine(sb)
	this.writeTableDeclParseFunc(sb, tableDef, indent)
	if tableDef.TableKeyType == TableKeyType_SingleKey {
		this.writeTableDeclGetRowFunc(sb, tableDef, indent)
	} else if tableDef.TableKeyType == TableKeyType_SetKey {
		this.writeTableDeclGetRowSetFunc(sb, tableDef, indent)
	}

	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDeclRowClassDecl(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	this.writeLineFormat(sb,
		"%s    public sealed class Row",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	for _, def := range tableDef.Columns {
		csharpType := this.getTableColumnCSharpType(def)
		defaultValue := this.getTableColumnCSharpTypeDefaultValue(def)
		if len(defaultValue) > 10 {
			this.writeLineFormat(sb,
				"%s        public %s %s =",
				indent, csharpType, def.Name)
			this.writeLineFormat(sb,
				"%s            %s;",
				indent, defaultValue)
		} else {
			this.writeLineFormat(sb,
				"%s        public %s %s = %s;",
				indent, csharpType, def.Name, defaultValue)
		}
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDeclMemberDecl(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	if tableDef.TableKeyType == TableKeyType_SingleKey {
		keyType := this.getTableColumnCSharpType(tableDef.TableKey)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.List<Row> rows =",
			indent)
		this.writeLineFormat(sb,
			"%s        new System.Collections.Generic.List<Row>();",
			indent)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.Dictionary<%s, Row> rowIndex =",
			indent, keyType)
		this.writeLineFormat(sb,
			"%s        new System.Collections.Generic.Dictionary<%s, Row>();",
			indent, keyType)
	} else if tableDef.TableKeyType == TableKeyType_SetKey {
		keyType := this.getTableColumnCSharpType(tableDef.TableKey)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.List<",
			indent)
		this.writeLineFormat(sb,
			"%s        System.Collections.Generic.List<Row>> rowSets =",
			indent)
		this.writeLineFormat(sb,
			"%s            new System.Collections.Generic.List<",
			indent)
		this.writeLineFormat(sb,
			"%s                System.Collections.Generic.List<Row>>();",
			indent)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.Dictionary<",
			indent)
		this.writeLineFormat(sb,
			"%s        %s, System.Collections.Generic.List<Row>> rowSetIndex =",
			indent, keyType)
		this.writeLineFormat(sb,
			"%s            new System.Collections.Generic.Dictionary<",
			indent)
		this.writeLineFormat(sb,
			"%s                %s, System.Collections.Generic.List<Row>>();",
			indent, keyType)
	}
}

func (this *CSharpCodeGenerator) writeTableDeclParseFunc(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	this.writeLineFormat(sb,
		"%s    public bool Parse(string text, out string errorInfo)",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        Brickred.Table.LineReader r = new Brickred.Table.LineReader(text);",
		indent)
	this.writeLineFormat(sb,
		"%s        System.Collections.Generic.List<string> lineBuffer = null;",
		indent)
	this.writeLineFormat(sb,
		"%s        int columnCountReq = %d;",
		indent, len(tableDef.Columns))

	this.writeTableDeclParseFuncReadCommentLine(sb, indent)
	this.writeTableDeclParseFuncReadNameLine(sb, tableDef, indent)

	if tableDef.TableKeyType == TableKeyType_SingleKey {
		this.writeTableDeclParseFuncSingleKeyReadDataLine(
			sb, tableDef, indent)
	} else if tableDef.TableKeyType == TableKeyType_SetKey {
		this.writeTableDeclParseFuncSetKeyReadDataLine(
			sb, tableDef, indent)
	}

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s        errorInfo = \"\";",
		indent)
	this.writeLineFormat(sb,
		"%s        return true;",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDeclParseFuncReadCommentLine(
	sb *strings.Builder, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s        // read comment line",
		indent)
	this.writeLineFormat(sb,
		"%s        lineBuffer = r.NextLine();",
		indent)
	this.writeLineFormat(sb,
		"%s        if (lineBuffer == null) {",
		indent)
	this.writeLineFormat(sb,
		"%s            errorInfo = \"comment line is required\";",
		indent)
	this.writeLineFormat(sb,
		"%s            return false;",
		indent)
	this.writeLineFormat(sb,
		"%s        }",
		indent)
	this.writeLineFormat(sb,
		"%s        if (lineBuffer.Count != columnCountReq) {",
		indent)
	this.writeLineFormat(sb,
		"%s            errorInfo = string.Format(",
		indent)
	this.writeLineFormat(sb, ""+
		"%s                \"comment line column count {0} is invalid, "+
		"should be {1}\",",
		indent)
	this.writeLineFormat(sb,
		"%s                lineBuffer.Count, columnCountReq);",
		indent)
	this.writeLineFormat(sb,
		"%s            return false;",
		indent)
	this.writeLineFormat(sb,
		"%s        }",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDeclParseFuncReadNameLine(
	sb *strings.Builder, tableDef *TableDef, indent string) {
	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s        // read name line",
		indent)
	this.writeLineFormat(sb,
		"%s        lineBuffer = r.NextLine();",
		indent)
	this.writeLineFormat(sb,
		"%s        if (lineBuffer == null) {",
		indent)
	this.writeLineFormat(sb,
		"%s            errorInfo = \"name line is required\";",
		indent)
	this.writeLineFormat(sb,
		"%s            return false;",
		indent)
	this.writeLineFormat(sb,
		"%s        }",
		indent)
	this.writeLineFormat(sb,
		"%s        if (lineBuffer.Count != columnCountReq) {",
		indent)
	this.writeLineFormat(sb,
		"%s            errorInfo = string.Format(",
		indent)
	this.writeLineFormat(sb, "" +
		"%s                \"name line column count {0} is invalid, "+
		"should be {1}\",",
		indent)
	this.writeLineFormat(sb,
		"%s                lineBuffer.Count, columnCountReq);",
		indent)
	this.writeLineFormat(sb,
		"%s            return false;",
		indent)
	this.writeLineFormat(sb,
		"%s        }",
		indent)
	this.writeLineFormat(sb,
		"%s        {",
		indent)
	this.writeLineFormat(sb,
		"%s            int colNumber = 0;",
		indent)
	this.writeEmptyLine(sb)
	for _, def := range tableDef.Columns {
		this.writeLineFormat(sb,
			"%s            if (lineBuffer[colNumber++] != \"%s\") {",
			indent, def.Name)
		this.writeLineFormat(sb,
			"%s                errorInfo = string.Format(",
			indent)
		this.writeLineFormat(sb, ""+
			"%s                    \"column {0} should be named as `%s`\", "+
			"colNumber);",
			indent, def.Name)
		this.writeLineFormat(sb,
			"%s                return false;",
			indent)
		this.writeLineFormat(sb,
			"%s            }",
			indent)
	}
	this.writeLineFormat(sb,
		"%s        }",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDeclParseFuncSingleKeyReadDataLine(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s        // read data lines",
		indent)
	this.writeLineFormat(sb,
		"%s        int lineNumber = 3;",
		indent)
	this.writeLineFormat(sb,
		"%s        this.rows.Clear();",
		indent)
	this.writeLineFormat(sb,
		"%s        for (;;) {",
		indent)
	this.writeLineFormat(sb,
		"%s            lineBuffer = r.NextLine();",
		indent)
	this.writeLineFormat(sb,
		"%s            if (lineBuffer == null) {",
		indent)
	this.writeLineFormat(sb,
		"%s                break;",
		indent)
	this.writeLineFormat(sb,
		"%s            }",
		indent)
	this.writeLineFormat(sb,
		"%s            if (lineBuffer.Count != columnCountReq) {",
		indent)
	this.writeLineFormat(sb,
		"%s                errorInfo = string.Format(",
		indent)
	this.writeLineFormat(sb, ""+
		"%s                    \"line {0} column count {1} is invalid, "+
		"should be {2}\",",
		indent)
	this.writeLineFormat(sb,
		"%s                    lineNumber, lineBuffer.Count, columnCountReq);",
		indent)
	this.writeLineFormat(sb,
		"%s                return false;",
		indent)
	this.writeLineFormat(sb,
		"%s            }",
		indent)
	this.writeLineFormat(sb,
		"%s            if (lineBuffer[0].Length == 0) {",
		indent)
	this.writeLineFormat(sb,
		"%s                errorInfo = string.Format(",
		indent)
	this.writeLineFormat(sb,
		"%s                    \"line {0} key `%s` is empty\", lineNumber);",
		indent, tableDef.TableKey.Name)
	this.writeLineFormat(sb,
		"%s                return false;",
		indent)
	this.writeLineFormat(sb,
		"%s            }",
		indent)
	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s            Row row = new Row();",
		indent)
	this.writeLineFormat(sb,
		"%s            int colNumber = 0;",
		indent)
	this.writeEmptyLine(sb)
	this.writeTableDeclParseFuncParseColumns(sb, tableDef, indent)
	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s            if (GetRow(row.%s) != null) {",
		indent, tableDef.TableKey.Name)
	this.writeLineFormat(sb,
		"%s                errorInfo = string.Format(",
		indent)
	this.writeLineFormat(sb, ""+
		"%s                    \"line {0} key `%s` value {1} is duplicated\", "+
		"lineNumber, row.id);",
		indent, tableDef.TableKey.Name)
	this.writeLineFormat(sb,
		"%s                return false;",
		indent)
	this.writeLineFormat(sb,
		"%s            }",
		indent)
	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s            this.rows.Add(row);",
		indent)
	this.writeLineFormat(sb,
		"%s            this.rowIndex.Add(row.%s, row);",
		indent, tableDef.TableKey.Name)
	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s            lineNumber += 1;",
		indent)
	this.writeLineFormat(sb,
		"%s        }",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDeclParseFuncSetKeyReadDataLine(
	sb *strings.Builder, tableDef *TableDef, indent string) {
}

func (this *CSharpCodeGenerator) writeTableDeclParseFuncParseColumns(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	for _, def := range tableDef.Columns {
		isList := def.Type == TableColumnType_List
		var checkType TableColumnType
		if def.Type == TableColumnType_List {
			checkType = def.ListType
		} else {
			checkType = def.Type
		}

		if checkType == TableColumnType_Int {
			if isList {
				this.writeLineFormat(sb, ""+
					"%s            Brickred.Table.Util.ReadColumnIntList("+
					"lineBuffer[colNumber++], ref row.%s);",
					indent, def.Name)
			} else {
				this.writeLineFormat(sb, ""+
					"%s            row.%s = Brickred.Table.Util.Atoi("+
					"lineBuffer[colNumber++]);",
					indent, def.Name)
			}
		} else if checkType == TableColumnType_String {
			if isList {
				this.writeLineFormat(sb, ""+
					"%s            Brickred.Table.Util.ReadColumnStringList("+
					"lineBuffer[colNumber++], ref row.%s);",
					indent, def.Name)
			} else {
				this.writeLineFormat(sb,
					"%s            row.%s = lineBuffer[colNumber++];",
					indent, def.Name)
			}
		} else if checkType == TableColumnType_Struct {
			if isList {
				this.writeLineFormat(sb,
					"%s            if (Brickred.Table.Util.ReadColumnStructList(",
					indent)
				this.writeLineFormat(sb, ""+
					"%s                    lineBuffer[colNumber++], ref row.%s) "+
					"== false) {",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s                errorInfo = string.Format(",
					indent)
				this.writeLineFormat(sb, ""+
					"%s                    \"line {0} column `%s` value is invalid\", "+
					"lineNumber);",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s                return false;",
					indent)
				this.writeLineFormat(sb,
					"%s            }",
					indent)
			} else {
				this.writeLineFormat(sb,
					"%s            if (row.%s.Parse(lineBuffer[colNumber++]) == false) {",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s                errorInfo = string.Format(",
					indent)
				this.writeLineFormat(sb, ""+
					"%s                    \"line {0} column `%s` value is invalid\", "+
					"lineNumber);",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s                return false;",
					indent)
				this.writeLineFormat(sb,
					"%s                return false;",
					indent)
				this.writeLineFormat(sb,
					"%s            }",
					indent)
			}
		}
	}
}

func (this *CSharpCodeGenerator) writeTableDeclGetRowFunc(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	csharpType := this.getTableColumnCSharpType(tableDef.TableKey)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public Row GetRow(%s key)",
		indent, csharpType)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        Row row = null;",
		indent)
	this.writeLineFormat(sb,
		"%s        if (this.rowIndex.TryGetValue(key, out row) == false) {",
		indent)
	this.writeLineFormat(sb,
		"%s            return null;",
		indent)
	this.writeLineFormat(sb,
		"%s        }",
		indent)
	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s        return row;",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeTableDeclGetRowSetFunc(
	sb *strings.Builder, tableDef *TableDef, indent string) {
}
