package lib

import (
	"fmt"
	"path/filepath"
	"strings"
)

type CSharpCodeGenerator struct {
	BaseCodeGenerator
}

func NewCSharpCodeGenerator() *CSharpCodeGenerator {
	newObj := new(CSharpCodeGenerator)

	return newObj
}

func (this *CSharpCodeGenerator) Close() {
	this.close()
}

func (this *CSharpCodeGenerator) Generate(
	descriptor *TableDescriptor,
	reader string, outputDir string, newLineType NewLineType) bool {

	this.init(descriptor, reader, newLineType)

	for _, def := range this.descriptor.GlobalStructs {
		filePath := filepath.Join(outputDir, def.Name+".cs")
		fileContent := this.generateGlobalStructFile(def)
		if UtilWriteAllText(filePath, fileContent) == false {
			return false
		}
	}

	for _, def := range this.descriptor.Tables {
		filePath := filepath.Join(outputDir, def.Name+".cs")
		fileContent := this.generateTableFile(def)
		if UtilWriteAllText(filePath, fileContent) == false {
			return false
		}
	}

	return true
}

func (this *CSharpCodeGenerator) getStructFieldCSharpType(
	fieldDef *StructFieldDef) string {

	csharpType := ""
	if fieldDef.Type == StructFieldType_Int {
		csharpType = "int"
	} else if fieldDef.Type == StructFieldType_String {
		csharpType = "string"
	}

	return csharpType
}

func (this *CSharpCodeGenerator) getStructFieldCSharpTypeDefaultValue(
	fieldDef *StructFieldDef) string {

	defaultValue := ""
	if fieldDef.Type == StructFieldType_Int {
		defaultValue = "0"
	} else if fieldDef.Type == StructFieldType_String {
		defaultValue = "\"\""
	}

	return defaultValue
}

func (this *CSharpCodeGenerator) getTableColumnCSharpType(
	columnDef *TableColumnDef) string {

	var checkType TableColumnType
	if columnDef.Type == TableColumnType_List {
		checkType = columnDef.ListType
	} else {
		checkType = columnDef.Type
	}

	csharpType := ""
	if checkType == TableColumnType_Int {
		csharpType = "int"
	} else if checkType == TableColumnType_String {
		csharpType = "string"
	} else if checkType == TableColumnType_Struct {
		csharpType = columnDef.RefStructDef.Name
	}

	if columnDef.Type == TableColumnType_List {
		return fmt.Sprintf("System.Collections.Generic.List<%s>", csharpType)
	} else {
		return csharpType
	}
}

func (this *CSharpCodeGenerator) getTableColumnCSharpTypeDefaultValue(
	columnDef *TableColumnDef) string {

	defaultValue := ""
	if columnDef.Type == TableColumnType_Int {
		defaultValue = "0"
	} else if columnDef.Type == TableColumnType_String {
		defaultValue = "\"\""
	} else if columnDef.Type == TableColumnType_Struct ||
		columnDef.Type == TableColumnType_List {
		defaultValue = fmt.Sprintf("new %s()",
			this.getTableColumnCSharpType(columnDef))
	}

	return defaultValue
}

func (this *CSharpCodeGenerator) generateGlobalStructFile(
	structDef *StructDef) string {

	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeNamespaceDeclStart(&sb)

	indent := this.getIndent()
	this.writeOneStructDecl(&sb, structDef, indent)

	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CSharpCodeGenerator) generateTableFile(
	tableDef *TableDef) string {

	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeNamespaceDeclStart(&sb)

	indent := this.getIndent()
	this.writeOneTableDecl(&sb, tableDef, indent)

	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CSharpCodeGenerator) getIndent() string {
	if _, ok := this.descriptor.Readers[this.reader]; ok {
		return "    "
	} else {
		return ""
	}
}

func (this *CSharpCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb,
		"/*")
	this.writeLine(sb,
		" * Generated by brickred table compiler.")
	this.writeLine(sb,
		" * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb,
		" */")
}

func (this *CSharpCodeGenerator) writeNamespaceDeclStart(
	sb *strings.Builder) {

	readerDef, ok := this.descriptor.Readers[this.reader]
	if ok == false {
		return
	}

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"namespace %s",
		readerDef.Namespace)
	this.writeLine(sb,
		"{")
}

func (this *CSharpCodeGenerator) writeNamespaceDeclEnd(
	sb *strings.Builder) {

	_, ok := this.descriptor.Readers[this.reader]
	if ok == false {
		return
	}

	this.writeLine(sb,
		"}")
}

func (this *CSharpCodeGenerator) writeOneStructDecl(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if structDef.ParentRef != nil {
		indent += "    "
	}

	this.writeLineFormat(sb,
		"%spublic sealed class %s : Brickred.Table.BaseStruct",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)

	this.writeOneStructDeclFieldDecl(sb, structDef, indent)
	this.writeOneStructDeclParseFunc(sb, structDef, indent)

	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclFieldDecl(
	sb *strings.Builder, structDef *StructDef, indent string) {

	for _, def := range structDef.Fields {
		csharpType := this.getStructFieldCSharpType(def)
		defaultValue := this.getStructFieldCSharpTypeDefaultValue(def)
		this.writeLineFormat(sb,
			"%s    public %s %s = %s;",
			indent, csharpType, def.Name, defaultValue)
	}
}

func (this *CSharpCodeGenerator) writeOneStructDeclParseFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if len(structDef.Fields) > 0 {
		this.writeEmptyLine(sb)
	}
	this.writeLineFormat(sb,
		"%s    public override bool Parse(string text)",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	if len(structDef.Fields) <= 0 {
		this.writeLineFormat(sb,
			"%s        return true;",
			indent)
	} else {
		this.writeLineFormat(sb,
			"%s        Brickred.Table.ColumnSpliter s =",
			indent)
		this.writeLineFormat(sb,
			"%s            new Brickred.Table.ColumnSpliter(text, ';');",
			indent)
		this.writeEmptyLine(sb)

		for _, def := range structDef.Fields {
			if def.Type == StructFieldType_Int {
				this.writeLineFormat(sb,
					"%s        if (s.NextInt(ref this.%s) == false) {",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s            return false;",
					indent)
				this.writeLineFormat(sb,
					"%s        }",
					indent)
			} else if def.Type == StructFieldType_String {
				this.writeLineFormat(sb,
					"%s        if (s.NextString(ref this.%s) == false) {",
					indent, def.Name)
				this.writeLineFormat(sb,
					"%s            return false;",
					indent)
				this.writeLineFormat(sb,
					"%s        }",
					indent)
			}
		}

		this.writeLineFormat(sb,
			"%s        if (s.NextString()) {",
			indent)
		this.writeLineFormat(sb,
			"%s            return false;",
			indent)
		this.writeLineFormat(sb,
			"%s        }",
			indent)
		this.writeEmptyLine(sb)
		this.writeLineFormat(sb,
			"%s        return true;",
			indent)
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneTableDecl(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	this.writeLineFormat(sb,
		"%spublic sealed class %s",
		indent, tableDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)

	for _, def := range tableDef.LocalStructs {
		this.writeOneStructDecl(sb, def, indent)
		this.writeEmptyLine(sb)
	}

	this.writeOneTableDeclRowClassDecl(sb, tableDef, indent)
	this.writeEmptyLine(sb)
	this.writeOneTableDeclMemberDecl(sb, tableDef, indent)
	this.writeEmptyLine(sb)
	this.writeOneTableDeclParseFunc(sb, tableDef, indent)

	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeOneTableDeclRowClassDecl(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	this.writeLineFormat(sb,
		"%s    public sealed class Row",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	for _, def := range tableDef.Columns {
		csharpType := this.getTableColumnCSharpType(def)
		defaultValue := this.getTableColumnCSharpTypeDefaultValue(def)
		if len(defaultValue) > 10 {
			this.writeLineFormat(sb,
				"%s        public %s %s =",
				indent, csharpType, def.Name)
			this.writeLineFormat(sb,
				"%s            %s;",
				indent, defaultValue)
		} else {
			this.writeLineFormat(sb,
				"%s        public %s %s = %s;",
				indent, csharpType, def.Name, defaultValue)
		}
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneTableDeclMemberDecl(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	if tableDef.TableKeyType == TableKeyType_SingleKey {
		keyType := this.getTableColumnCSharpType(tableDef.TableKey)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.List<Row> rows =",
			indent)
		this.writeLineFormat(sb,
			"%s        new System.Collections.Generic.List<Row>();",
			indent)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.Dictionary<%s, Row> rowIndex =",
			indent, keyType)
		this.writeLineFormat(sb,
			"%s        new System.Collections.Generic.Dictionary<%s, Row>();",
			indent, keyType)
	} else if tableDef.TableKeyType == TableKeyType_SetKey {
		keyType := this.getTableColumnCSharpType(tableDef.TableKey)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.List<",
			indent)
		this.writeLineFormat(sb,
			"%s        System.Collections.Generic.List<Row>> rowSets =",
			indent)
		this.writeLineFormat(sb,
			"%s            new System.Collections.Generic.List<",
			indent)
		this.writeLineFormat(sb,
			"%s                System.Collections.Generic.List<Row>>();",
			indent)
		this.writeLineFormat(sb,
			"%s    private System.Collections.Generic.Dictionary<",
			indent)
		this.writeLineFormat(sb,
			"%s        %s, System.Collections.Generic.List<Row>> rowSetIndex =",
			indent, keyType)
		this.writeLineFormat(sb,
			"%s            new System.Collections.Generic.Dictionary<",
			indent)
		this.writeLineFormat(sb,
			"%s                %s, System.Collections.Generic.List<Row>>();",
			indent, keyType)
	}
}

func (this *CSharpCodeGenerator) writeOneTableDeclParseFunc(
	sb *strings.Builder, tableDef *TableDef, indent string) {

	this.writeLineFormat(sb,
		"%s    public bool Parse(string text, out string errorInfo)",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return true;",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}
